Filter for responses items in AbstractSchema.php
When creating custom product class there are places in ProductSchema.php and CartItemSchema.php where items are forced to be \WC_Product $product and that cast cause errors for the custom product class. With this filter we can be able to exclude our custom product class from that Schema responses.

Fatal error: Uncaught TypeError: Argument 1 passed to Automattic\WooCommerce\StoreApi\Schemas\V1\ProductSchema::get_low_stock_remaining() must be an instance of WC_Product, instance of WC_Product_Room given, called in D:\projects\test\wp-content\plugins\woocommerce\packages\woocommerce-blocks\src\StoreApi\Schemas\V1\CartItemSchema.php on line 347 and defined in D:\projects\test\wp-content\plugins\woocommerce\packages\woocommerce-blocks\src\StoreApi\Schemas\V1\ProductSchema.php:516